<form action="<?= $block->getFormAction() ?>" method="post">
    <label for="email">Email:</label>
    <input type="email" name="email" id="email" required />
    <br />0
    <label for="name">First Name:</label>
    <input type="text" name="name" id="name" required />
    <br />
    <label for="name">Last Name:</label>
    <input type="text" name="lname" id="name" required />
    <br />
    <label for="email">SchoolName:</label>
    <input type="email" name="school" id="email" required />
    <br />
    <button type="submit">Submit</button>
</form>
